### ISSUE TITLE
Mac环境导入creator V1.6.2版本 init报错

### ISSUE THREAD

**Issue by SvenNJ** [cocos-creator/tutorial-hot-update#9]
2017-10-27T09:22:29.555Z - normal: Initializing project /Users/XXXXX/creator/tutorial-hot-update
2017-10-27T09:22:29.559Z - normal: Loading packages
2017-10-27T09:22:29.574Z - normal: [Lua Support] version 1.1.6
2017-10-27T09:22:29.576Z - success: creator-lua-support loaded
2017-10-27T09:22:29.579Z - success: hot-update loaded
2017-10-27T09:22:29.579Z - normal: Watching packages
2017-10-27T09:22:29.628Z - normal: Run Application
2017-10-27T09:22:33.938Z - failed: [db-task][init] Failed to post import asset /Users/XXXXX/creator/tutorial-hot-update/assets/font/stake_number.fnt, message: TypeError: Cannot read property 'uuid' of undefined
    at BitmapFontMeta.postImport (/Applications/CocosCreator.app/Contents/Resources/app.asar/editor/share/assets/meta/bitmap-font.js:1:1139)
    at Async.series.e (/Applications/CocosCreator.app/Contents/Resources/app.asar/asset-db/lib/tasks.js:1:5804)
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:718:13
    at iterate (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:281:9)
    at _parallel (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:739:9)
    at _postImportAsset (/Applications/CocosCreator.app/Contents/Resources/app.asar/asset-db/lib/tasks.js:1:5734)
    at Async.eachLimit.Async.ensureAsync (/Applications/CocosCreator.app/Contents/Resources/app.asar/asset-db/lib/tasks.js:1:7544)
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:1213:16
2017-10-27T09:22:34.467Z - success: preview server running at http://localhost:7456
2017-10-27T09:22:39.903Z - normal: 1.6.2

**Comment by SvenNJ** [comment]
无法体验这个热更新教程， 求教~

**Comment by iamzuijiasunyou** [comment]
1.9.1也报这个错误。。
